service: mmi-alert
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  profile: serverless
functions:
  mmiAlert:
    handler: handler.mmiAlert
    events:
    - schedule:
        rate: cron(30 5 ? * MON-FRI *)
        enabled: true
