service: mmi-alert
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  profile: serverless
functions:
  mmiAlert:
    handler: handler.mmiAlert
    events:
    - schedule:
        rate: cron(30 5 ? * MON-FRI *)
        enabled: true
package:
  exclude:
    - images/**
    - README.md
    - package.json
    - package-lock.json
    - LICENSE
